# Generated by Django 5.0.1 on 2024-01-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepostnews',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
