# Generated by Django 5.0.1 on 2024-01-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0005_alter_homepostnews_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepostnews',
            name='url',
        ),
    ]
