# Generated by Django 5.0.1 on 2024-01-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0006_remove_homepostnews_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepostnews',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
