# Generated by Django 5.0.1 on 2024-01-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0010_homepostnews_urls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepostnews',
            old_name='urls',
            new_name='url',
        ),
    ]
