# Generated by Django 5.0.1 on 2024-01-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0012_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ism',
        ),
    ]
