# Generated by Django 5.0.1 on 2024-01-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0015_alter_contact_ism'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ism',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='xabar',
        ),
    ]
