# Generated by Django 5.0.1 on 2024-01-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0016_remove_contact_ism_remove_contact_xabar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
