# Generated by Django 5.0.1 on 2024-01-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0017_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlahva', models.CharField(max_length=100)),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='media')),
                ('matn', models.TextField()),
            ],
        ),
    ]
