# Generated by Django 5.0.1 on 2024-01-03 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0018_aboutme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='sarlahva',
            new_name='sarlavha',
        ),
    ]
