# Generated by Django 5.0.1 on 2024-01-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogone', '0019_rename_sarlahva_aboutme_sarlavha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
